# Generated by Django 3.2.7 on 2021-10-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuttPutt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tournament_scheduled', models.BooleanField(default=False)),
                ('prize_pool', models.PositiveIntegerField()),
                ('sponsor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DrinkOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=12)),
                ('drink', models.CharField(max_length=30)),
                ('hole_number', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('cost', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=14)),
                ('score_hole_1', models.PositiveSmallIntegerField(default=0)),
                ('score_hole_2', models.PositiveSmallIntegerField(default=0)),
                ('score_hole_3', models.PositiveSmallIntegerField(default=0)),
                ('score_hole_4', models.PositiveSmallIntegerField(default=0)),
                ('score_hole_5', models.PositiveSmallIntegerField(default=0)),
                ('score_hole_6', models.PositiveSmallIntegerField(default=0)),
                ('score_hole_7', models.PositiveSmallIntegerField(default=0)),
                ('score_hole_8', models.PositiveSmallIntegerField(default=0)),
                ('score_hole_9', models.PositiveSmallIntegerField(default=0)),
                ('score_hole_10', models.PositiveSmallIntegerField(default=0)),
                ('score_hole_11', models.PositiveSmallIntegerField(default=0)),
                ('score_hole_12', models.PositiveSmallIntegerField(default=0)),
                ('score_hole_13', models.PositiveSmallIntegerField(default=0)),
                ('score_hole_14', models.PositiveSmallIntegerField(default=0)),
                ('score_hole_15', models.PositiveSmallIntegerField(default=0)),
                ('score_hole_16', models.PositiveSmallIntegerField(default=0)),
                ('score_hole_17', models.PositiveSmallIntegerField(default=0)),
                ('score_hole_18', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('PL', 'Player'), ('SP', 'Sponsor'), ('MA', 'Manager'), ('DM', 'DrinkMeister')], default='PL', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
