# Generated by Django 3.2.7 on 2021-10-05 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PuttPutt', '0002_auto_20211004_1805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drinks',
            new_name='Drink',
        ),
    ]
