# Generated by Django 3.1.7 on 2021-10-27 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PuttPutt', '0003_rename_drinks_drink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
