# Generated by Django 3.1.7 on 2021-11-21 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuttPutt', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=datetime.date(2021, 11, 21)),
        ),
    ]
