# Generated by Django 3.1.7 on 2021-11-21 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PuttPutt', '0006_tournament_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
