# Generated by Django 3.2.9 on 2021-12-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuttPutt', '0007_auto_20211121_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=14)),
                ('drink', models.CharField(max_length=30)),
                ('hole_number', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='DrinkOrders',
        ),
    ]
