# Generated by Django 3.2.9 on 2021-12-06 01:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PuttPutt', '0008_auto_20211205_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkorder',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
